# Image for the FTP server
#
# If an SFTP is needed in the future, it could be set up with this image. 
# This docker compose uses the SFTP Docker image found here:
# https://hub.docker.com/r/atmoz/sftp

version: '3'

# Usage example: https://github.com/stilliard/docker-pure-ftpd/wiki/Docker-stack-with-Wordpress-&-FTP

services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      # remember to replace /folder_on_disk/ with the path to 
      # where you want to store the files on the host machine
      - "/home/manuel/Desktop/data:/home/data/"
      - "/home/manuel/Desktop/passwd:/etc/pure-ftpd/passwd"
    # uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
    #      - "/folder_on_disk/ssl:/etc/ssl/private/"
    # or ssl/tls with Let's Encrypt (cert and key as two files)
    #      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
    #      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: manuel
      FTP_USER_PASS: testpass
      FTP_USER_HOME: /home/manuel
    # also for ssl/tls:
    #      ADDED_FLAGS: "--tls=2"
    restart: always
